"""initial migration

Revision ID: 17406c2735a3
Revises: 
Create Date: 2024-06-29 20:53:53.512355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17406c2735a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_migrate_1vn_student',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=15), nullable=True, comment='姓名'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_migrate_1vn_student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_migrate_1vn_student_name'), ['name'], unique=False)

    op.create_table('tb_migrate_1vn_student_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='地址名称'),
    sa.Column('province', sa.String(length=50), nullable=True, comment='省份'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='地区'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='详细地址'),
    sa.Column('mobile', sa.String(length=15), nullable=True, comment='收货人电话'),
    sa.Column('stu_id', sa.Integer(), nullable=True, comment='student外键'),
    sa.ForeignKeyConstraint(['stu_id'], ['tb_migrate_1vn_student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_migrate_1vn_student_info')
    with op.batch_alter_table('tb_migrate_1vn_student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_migrate_1vn_student_name'))

    op.drop_table('tb_migrate_1vn_student')
    # ### end Alembic commands ###
