"""modify address comment

Revision ID: cf1b53c9137e
Revises: 17406c2735a3
Create Date: 2024-06-29 21:01:51.226471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf1b53c9137e'
down_revision = '17406c2735a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_migrate_1vn_student_info', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=500),
               comment='收货详细地址',
               existing_comment='详细地址',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_migrate_1vn_student_info', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=500),
               comment='详细地址',
               existing_comment='收货详细地址',
               existing_nullable=True)

    # ### end Alembic commands ###
